### ISSUE TITLE
documentation seems broken

### ISSUE THREAD

**Issue by Sinewyk** [mostjs-community/most-subject#18]
Coming from RxJS in need of performance, the subject feature seems like the most powerful observable factory primitive to actually do whatever we want. I found this and doc is broken :cry: .

Please fix it ? :laughing:

**Comment by TylorS** [comment]
Hi @Sinewyk sorry, it is in fact broken. The api doc generation generates links that gh-pages doesn't seem to like or want to use. I'll definitely look into fixing that.

**Comment by TylorS** [comment]
@Sinewyk https://github.com/TylorS/most-subject#handwitten-documentation-

I added some stuff quickly to the README, probably better than what documentation generator could do anyways. Hope it helps you.

**Comment by TylorS** [comment]
I'll keep this open as a reminder, but I won't be able to actually fix this for a while. I'll be travelling for a little while.

**Comment by TylorS** [comment]
Closing this as handwritten docs are probably better
