### ISSUE TITLE
Circular Dependencies

### ISSUE THREAD

**Issue by partially-applied** [mostjs-community/most-subject#28]
In your docs there is a mention of circular dependencies. 

I think I am not sure what you mean by it. 

Is this an example of circular dependency

``` livescript

{subject} = require 'most-subject'


stream = subject!


stream.map (vals) -> 

    stream.next vals

.drain!

stream.next 1 

```

**Comment by TylorS** [comment]
```js
const proxy = subject()

const stream = proxy.map(...)

stream.subscribe(proxy)
```

**Comment by partially-applied** [comment]
Seems to be similar. 

So is this the reasoning why its a bad idea to use subjects generally - until you have a way to prevent circular dependencies from breaking your application ?

**Comment by TylorS** [comment]
Sorry for not responding sooner. Circular dependencies are not the reason why subjects are not recommended, but because using subjects is imperative and often side-effectful, whereas most.js promotes using declarative approaches.

**Comment by TylorS** [comment]
I'm going to close this as it's a stale discussion. Feel free to reopen if you like.

**Comment by partially-applied** [comment]
thanks for closing it

On Thu, Nov 10, 2016 at 1:13 AM, Tylor Steinberger <notifications@github.com
